ERROR - 2023-06-19 11:41:20 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 11:41:20 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 11:42:12 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 11:42:12 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:11:19 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:11:19 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:15:56 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:15:56 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:16:44 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:16:44 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:17:38 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:17:38 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:18:14 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:18:14 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:20:03 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:20:03 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:21:03 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:21:03 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:12 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:12 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:20 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id20933006_usuario1313'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3346, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-19 12:24:41 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'id20933006_usua...', Object(SensitiveParameterValue), 'id20933006_list...', 3306, '', 0)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#7 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ListaDeTarefas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ListaDeTarefas\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ListaDeTarefas\app\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#3 C:\xampp\htdocs\ListaDeTarefas\app\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
#4 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
#5 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
#6 C:\xampp\htdocs\ListaDeTarefas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ListaDeTarefas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-06-19 12:24:41 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\BD_Model.php(11): CodeIgniter\Database\BaseConnection->query('SELECT * FROM tarefa')
 3 APPPATH\Controllers\ConsultarDados.php(12): App\Models\BD_Model->exibirTarefas()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ConsultarDados->exibirTarefas()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ConsultarDados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
